### ISSUE TITLE
Accept a psql connection on unix domain socket

### ISSUE THREAD

**Issue by getogrand** [SaturDJang/warp#100]
Following error is occurred when you run the `python mange.py test` command.

```shell
(warp) {13:51}~/Dropbox/SaturDJang Team Folder/warp:master ✓ ➭ python manage.py test
Creating test database for alias 'default'...
/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/postgresql/base.py:247: RuntimeWarning: Normally Django will use a connection to the 'postgres' database to avoid running initialization queries against the production database when it's not needed (for example, when running tests). Django was unable to create a connection to the 'postgres' database and will use the default database instead.
  RuntimeWarning

Traceback (most recent call last):
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/test/runner.py", line 532, in run_tests
    old_config = self.setup_databases()
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/test/runner.py", line 482, in setup_databases
    self.parallel, **kwargs
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/test/runner.py", line 726, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 56, in create_test_db
    self._create_test_db(verbosity, autoclobber, keepdb)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 165, in _create_test_db
    with self._nodb_connection.cursor() as cursor:
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/wonyoungju/.pyenv/versions/warp/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by getogrand** [comment]
Resolved in #103.
